push = require 'lib.push'
Class = require 'lib.class'
require 'asset.resource'
require 'asset.constants'
require 'asset.Bird'
require 'asset.Pipe'
require 'asset.PipePair'
require 'asset.Statemachine'
require 'states.BaseState'
require 'states.CountdownState'
require 'states.PlayState'
require 'states.ScoreState'
require 'states.TitleScreenState'

-- require 'assets.gfx.assets'